"""
Harness Generator for Middleware/Firmware Fuzzing

Generates fuzzing harnesses for various firmware targets:
- 3P3Z filters (power control)
- Type 1/2/3 compensators
- PID controllers
- Generic C functions

The harness wraps the target function so AFL++ can fuzz it.

Usage:
    generator = HarnessGenerator(constraints_file="3p3z_params.json")
    harness_code = generator.generate_3p3z_harness()
    generator.save_harness("harness_3p3z.c")
"""

import os
import json
from pathlib import Path
from typing import Dict, List, Optional, Any
from dataclasses import dataclass
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


@dataclass
class FuzzingTarget:
    """Definition of a fuzzing target function"""
    name: str
    signature: str
    parameters: List[Dict[str, Any]]
    return_type: str
    header_file: str
    description: str = ""


class HarnessGenerator:
    """
    Generates AFL++ fuzzing harnesses for firmware targets.
    
    Supports:
    - 3P3Z filter blocks
    - Type 1/2/3 compensators
    - PID controllers
    - Custom C functions
    """
    
    def __init__(self, constraints_file: Optional[str] = None):
        """
        Initialize harness generator.
        
        Args:
            constraints_file: Path to JSON file with parameter constraints
        """
        self.constraints = {}
        if constraints_file and Path(constraints_file).exists():
            with open(constraints_file, 'r') as f:
                data = json.load(f)
                # Extract parameters into dict by name
                params = data.get('parameters', {})
                # Handle both list format and dict format
                if isinstance(params, list):
                    for param in params:
                        self.constraints[param['name']] = param
                elif isinstance(params, dict):
                    self.constraints = params
    
    def generate_3p3z_harness(
        self,
        include_path: str = "filter_3p3z.h",
        function_name: str = "filter_3p3z_run"
    ) -> str:
        """
        Generate fuzzing harness for 3P3Z filter.
        
        3P3Z equation: y[n] = Σ(A*y[n-i]) + Σ(B*x[n-j])
        
        Args:
            include_path: Path to the 3P3Z header file
            function_name: Name of the function to fuzz
            
        Returns:
            C code for the fuzzing harness
        """
        harness = f'''/**
 * AFL++ Fuzzing Harness for 3P3Z Filter
 * Generated by LLM Firmware Fuzzer
 * 
 * Compile with:
 *   afl-clang-fast harness_3p3z.c filter_3p3z.c -o fuzz_3p3z
 * 
 * Run with:
 *   afl-fuzz -i seeds/ -o findings/ ./fuzz_3p3z @@
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include "{include_path}"

// Q23 fixed-point format: 1 sign bit + 8 integer bits + 23 fractional bits
#define Q23_SCALE (1 << 23)
#define Q23_TO_FLOAT(x) ((float)(x) / Q23_SCALE)
#define FLOAT_TO_Q23(x) ((int32_t)((x) * Q23_SCALE))

// Parameter structure matching the fuzzer input
typedef struct __attribute__((packed)) {{
    // X coefficients (cx_q23[0-3])
    int32_t cx_q23[4];
    
    // Y coefficients (cy_q23[0-2])
    int32_t cy_q23[3];
    
    // Scale factors
    uint8_t scaleCx;
    uint8_t scaleCy;
    
    // Gain factors
    uint8_t gIn;
    uint8_t gOut;
    
    // Limits
    int32_t limit_max;
    int32_t limit_min;
    
    // Input sample
    int32_t input_sample;
}} Fuzz3P3ZParams;

// Validate parameters are within acceptable ranges
int validate_params(const Fuzz3P3ZParams* params) {{
    // cx_q23 should be in [-1, 1) which is [-Q23_SCALE, Q23_SCALE) in Q23
    for (int i = 0; i < 4; i++) {{
        if (params->cx_q23[i] < -Q23_SCALE || params->cx_q23[i] >= Q23_SCALE) {{
            return 0; // Out of range
        }}
    }}
    
    // cy_q23 should be in [-1, 1)
    for (int i = 0; i < 3; i++) {{
        if (params->cy_q23[i] < -Q23_SCALE || params->cy_q23[i] >= Q23_SCALE) {{
            return 0;
        }}
    }}
    
    // Scale factors: 0-7
    if (params->scaleCx > 7 || params->scaleCy > 7) {{
        return 0;
    }}
    
    // Gain factors
    if (params->gIn > 3 || params->gOut > 7) {{
        return 0;
    }}
    
    return 1; // Valid
}}

// Main fuzzing entry point
int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {{
    // Check minimum size
    if (size < sizeof(Fuzz3P3ZParams)) {{
        return 0;
    }}
    
    // Cast input to parameter structure
    const Fuzz3P3ZParams* params = (const Fuzz3P3ZParams*)data;
    
    // Log whether params are in valid range (for categorization)
    int in_range = validate_params(params);
    
    // Initialize filter state (static to maintain across calls)
    static int32_t x_history[4] = {{0}};
    static int32_t y_history[3] = {{0}};
    
    // Reset history for each new input
    memset(x_history, 0, sizeof(x_history));
    memset(y_history, 0, sizeof(y_history));
    
    // Run the filter with fuzzed parameters
    // NOTE: Adapt this call to match your actual function signature
    int32_t result = {function_name}(
        params->cx_q23,
        params->cy_q23,
        params->scaleCx,
        params->scaleCy,
        params->gIn,
        params->gOut,
        params->limit_min,
        params->limit_max,
        params->input_sample,
        x_history,
        y_history
    );
    
    // Consume result to prevent optimization
    (void)result;
    (void)in_range;
    
    return 0;
}}

#ifndef FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION
// Standalone mode for testing with file input
int main(int argc, char** argv) {{
    if (argc != 2) {{
        fprintf(stderr, "Usage: %s <input_file>\\n", argv[0]);
        return 1;
    }}
    
    FILE* f = fopen(argv[1], "rb");
    if (!f) {{
        perror("fopen");
        return 1;
    }}
    
    uint8_t buffer[sizeof(Fuzz3P3ZParams) + 64];
    size_t size = fread(buffer, 1, sizeof(buffer), f);
    fclose(f);
    
    printf("Read %zu bytes\\n", size);
    
    int result = LLVMFuzzerTestOneInput(buffer, size);
    printf("Fuzzer returned: %d\\n", result);
    
    return result;
}}
#endif
'''
        return harness
    
    def generate_type2_compensator_harness(
        self,
        include_path: str = "compensator.h",
        function_name: str = "type2_compensator_run"
    ) -> str:
        """Generate harness for Type 2 compensator."""
        harness = f'''/**
 * AFL++ Fuzzing Harness for Type 2 Compensator
 * Generated by LLM Firmware Fuzzer
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include "{include_path}"

typedef struct __attribute__((packed)) {{
    // Type 2 has 2 poles and 1 zero
    float A1;
    float A2;
    float B0;
    float B1;
    float B2;
    float limit_max;
    float limit_min;
    float input_sample;
}} FuzzType2Params;

int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {{
    if (size < sizeof(FuzzType2Params)) {{
        return 0;
    }}
    
    const FuzzType2Params* params = (const FuzzType2Params*)data;
    
    static float x_history[3] = {{0}};
    static float y_history[2] = {{0}};
    
    memset(x_history, 0, sizeof(x_history));
    memset(y_history, 0, sizeof(y_history));
    
    float result = {function_name}(
        params->A1, params->A2,
        params->B0, params->B1, params->B2,
        params->limit_min, params->limit_max,
        params->input_sample,
        x_history, y_history
    );
    
    (void)result;
    return 0;
}}

#ifndef FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION
int main(int argc, char** argv) {{
    if (argc != 2) return 1;
    FILE* f = fopen(argv[1], "rb");
    if (!f) return 1;
    uint8_t buffer[256];
    size_t size = fread(buffer, 1, sizeof(buffer), f);
    fclose(f);
    return LLVMFuzzerTestOneInput(buffer, size);
}}
#endif
'''
        return harness
    
    def generate_pid_harness(
        self,
        include_path: str = "pid_controller.h",
        function_name: str = "pid_run"
    ) -> str:
        """Generate harness for PID controller."""
        harness = f'''/**
 * AFL++ Fuzzing Harness for PID Controller
 * Generated by LLM Firmware Fuzzer
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include "{include_path}"

typedef struct __attribute__((packed)) {{
    float Kp;           // Proportional gain
    float Ki;           // Integral gain
    float Kd;           // Derivative gain
    float setpoint;     // Target value
    float input;        // Current value
    float dt;           // Time step
    float limit_max;
    float limit_min;
}} FuzzPIDParams;

int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {{
    if (size < sizeof(FuzzPIDParams)) {{
        return 0;
    }}
    
    const FuzzPIDParams* params = (const FuzzPIDParams*)data;
    
    // Sanity check dt to avoid division by zero
    if (params->dt <= 0.0f || params->dt > 1.0f) {{
        return 0;
    }}
    
    static float integral = 0;
    static float prev_error = 0;
    
    integral = 0;
    prev_error = 0;
    
    float result = {function_name}(
        params->Kp, params->Ki, params->Kd,
        params->setpoint, params->input,
        params->dt,
        params->limit_min, params->limit_max,
        &integral, &prev_error
    );
    
    (void)result;
    return 0;
}}

#ifndef FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION
int main(int argc, char** argv) {{
    if (argc != 2) return 1;
    FILE* f = fopen(argv[1], "rb");
    if (!f) return 1;
    uint8_t buffer[256];
    size_t size = fread(buffer, 1, sizeof(buffer), f);
    fclose(f);
    return LLVMFuzzerTestOneInput(buffer, size);
}}
#endif
'''
        return harness
    
    def generate_generic_harness(
        self,
        target: FuzzingTarget,
        include_path: str = None
    ) -> str:
        """
        Generate a generic harness for any C function.
        
        Args:
            target: FuzzingTarget definition
            include_path: Header file path (uses target.header_file if None)
            
        Returns:
            C code for the fuzzing harness
        """
        if include_path is None:
            include_path = target.header_file
        
        # Build parameter struct
        struct_fields = ""
        for param in target.parameters:
            c_type = param.get('type', 'int32_t')
            name = param['name']
            struct_fields += f"    {c_type} {name};\n"
        
        # Build function call arguments
        args = ", ".join([f"params->{p['name']}" for p in target.parameters])
        
        harness = f'''/**
 * AFL++ Fuzzing Harness for {target.name}
 * {target.description}
 * Generated by LLM Firmware Fuzzer
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include "{include_path}"

typedef struct __attribute__((packed)) {{
{struct_fields}}} FuzzParams_{target.name};

int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {{
    if (size < sizeof(FuzzParams_{target.name})) {{
        return 0;
    }}
    
    const FuzzParams_{target.name}* params = (const FuzzParams_{target.name}*)data;
    
    {target.return_type} result = {target.name}({args});
    
    (void)result;
    return 0;
}}

#ifndef FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION
int main(int argc, char** argv) {{
    if (argc != 2) return 1;
    FILE* f = fopen(argv[1], "rb");
    if (!f) return 1;
    uint8_t buffer[1024];
    size_t size = fread(buffer, 1, sizeof(buffer), f);
    fclose(f);
    return LLVMFuzzerTestOneInput(buffer, size);
}}
#endif
'''
        return harness
    
    def generate_seed_from_constraints(
        self,
        output_dir: str = "data/corpus",
        count: int = 100
    ) -> List[str]:
        """
        Generate seed files based on parameter constraints.
        
        Creates binary files that can be used as initial AFL++ corpus.
        
        Args:
            output_dir: Directory to save seed files
            count: Number of seeds to generate
            
        Returns:
            List of created seed file paths
        """
        import struct

        # Deterministic seed generation (no randomness):
        # We generate a fixed set of valid + boundary values that cover the range.
        Path(output_dir).mkdir(parents=True, exist_ok=True)
        created_files: List[str] = []

        Q23_SCALE = 1 << 23

        def q23(frac: float) -> int:
            # clamp to [-1, 1) in Q23
            v = max(-0.9999999, min(0.9999999, frac))
            return int(v * Q23_SCALE)

        # Small deterministic suite
        patterns = [
            {"category": "valid", "cx": [q23(0.1)] * 4, "cy": [q23(0.05)] * 3, "scaleCx": 3, "scaleCy": 3, "gIn": 1, "gOut": 2,
             "limit_max": 1000, "limit_min": -1000, "input_sample": q23(0.01)},
            {"category": "boundary", "cx": [q23(0.999)] * 4, "cy": [q23(-0.999)] * 3, "scaleCx": 7, "scaleCy": 7, "gIn": 3, "gOut": 7,
             "limit_max": 2147483647, "limit_min": -2147483648, "input_sample": q23(0.999)},
            {"category": "boundary", "cx": [q23(-0.999)] * 4, "cy": [q23(0.999)] * 3, "scaleCx": 0, "scaleCy": 0, "gIn": 0, "gOut": 0,
             "limit_max": 0, "limit_min": 0, "input_sample": q23(-0.999)},
        ]

        # Repeat patterns deterministically up to count
        for i in range(count):
            p = patterns[i % len(patterns)]
            data = struct.pack(
                '<4i3iBBBBiii',
                p["cx"][0], p["cx"][1], p["cx"][2], p["cx"][3],
                p["cy"][0], p["cy"][1], p["cy"][2],
                int(p["scaleCx"]), int(p["scaleCy"]), int(p["gIn"]), int(p["gOut"]),
                int(p["limit_max"]), int(p["limit_min"]), int(p["input_sample"]),
            )

            filename = f"seed_3p3z_{p['category']}_{i:04d}.bin"
            filepath = Path(output_dir) / filename
            filepath.write_bytes(data)
            created_files.append(str(filepath))

        logger.info(f"Generated {count} deterministic seed files in {output_dir}")
        return created_files

    
    def save_harness(
        self,
        harness_code: str,
        output_path: str,
        makefile: bool = True
    ):
        """
        Save harness code to file with optional Makefile.
        
        Args:
            harness_code: The generated C code
            output_path: Path to save the harness
            makefile: Whether to generate a Makefile
        """
        # Save harness
        with open(output_path, 'w') as f:
            f.write(harness_code)
        logger.info(f"Saved harness to {output_path}")
        
        # Generate Makefile
        if makefile:
            output_dir = Path(output_path).parent
            harness_name = Path(output_path).stem
            
            makefile_content = f'''# Makefile for {harness_name}
# Generated by LLM Firmware Fuzzer

CC = afl-clang-fast
CFLAGS = -g -O2 -Wall -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION

# Target executable
TARGET = {harness_name}

# Source files (add your target source files here)
SRCS = {harness_name}.c
# SRCS += your_target.c

.PHONY: all clean fuzz

all: $(TARGET)

$(TARGET): $(SRCS)
\t$(CC) $(CFLAGS) -o $@ $^

# Run fuzzer
fuzz: $(TARGET)
\tmkdir -p findings
\tafl-fuzz -i seeds -o findings -V 300 -- ./$(TARGET) @@

# Build without fuzzing instrumentation (for testing)
debug: CFLAGS = -g -O0 -Wall
debug: CC = gcc
debug: $(TARGET)

clean:
\trm -f $(TARGET)
'''
            makefile_path = output_dir / "Makefile"
            with open(makefile_path, 'w') as f:
                f.write(makefile_content)
            logger.info(f"Saved Makefile to {makefile_path}")
    
    def generate_all_middleware_harnesses(self, output_dir: str = "src/harness/middleware"):
        """Generate harnesses for all common middleware targets."""
        Path(output_dir).mkdir(parents=True, exist_ok=True)
        
        # 3P3Z Filter
        harness_3p3z = self.generate_3p3z_harness()
        self.save_harness(harness_3p3z, f"{output_dir}/harness_3p3z.c")
        
        # Type 2 Compensator
        harness_type2 = self.generate_type2_compensator_harness()
        self.save_harness(harness_type2, f"{output_dir}/harness_type2.c")
        
        # PID Controller
        harness_pid = self.generate_pid_harness()
        self.save_harness(harness_pid, f"{output_dir}/harness_pid.c")
        
        # Generate seeds
        self.generate_seed_from_constraints(f"{output_dir}/seeds", count=50)
        
        logger.info(f"Generated all middleware harnesses in {output_dir}")


# ===========================================================================
# USAGE EXAMPLE
# ===========================================================================

if __name__ == "__main__":
    print("="*60)
    print("Harness Generator for Middleware Fuzzing")
    print("="*60)
    
    # Create generator
    generator = HarnessGenerator(constraints_file="data/constraints/3p3z_parameters.json")
    
    # Generate 3P3Z harness
    print("\nGenerating 3P3Z harness...")
    harness = generator.generate_3p3z_harness()
    
    # Save to file
    output_dir = Path("src/harness/generated")
    output_dir.mkdir(parents=True, exist_ok=True)
    
    generator.save_harness(harness, str(output_dir / "harness_3p3z.c"))
    
    # Generate seeds
    print("\nGenerating seed files...")
    seeds = generator.generate_seed_from_constraints(
        str(output_dir / "seeds"),
        count=20
    )
    print(f"Created {len(seeds)} seed files")
    
    # Show harness preview
    print("\n" + "="*60)
    print("Generated Harness Preview (first 50 lines):")
    print("="*60)
    for line in harness.split('\n')[:50]:
        print(line)
    print("...")
