"""CSV-based constraint extraction (offline-friendly).

This module exists to avoid hardcoding parameter ranges and to avoid dependency
on XLSX parsing libraries in sandboxed environments.

Expected CSV schema (as generated by `scripts/xlsx_to_csv_stdlib.py`):

Parameters,Type,Lower Limit,Upper Limit,Descriptive Limit,Bins
B0,post_build,-1,1,,3 bins (...)
...

All values are loaded as strings then normalized to numeric types where possible.
"""

from __future__ import annotations

import csv
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional


@dataclass(frozen=True)
class CsvConstraint:
    name: str
    kind: str  # pre_build|post_build
    min_value: Optional[float]
    max_value: Optional[float]
    description: str
    bins: str
    source: str

    def to_pipeline_dict(self) -> Dict[str, Any]:
        # Pipeline expects min/max and (optionally) valid_values.
        d: Dict[str, Any] = {
            "min": self.min_value,
            "max": self.max_value,
            "type": "float" if (self.min_value is not None or self.max_value is not None) else "unknown",
            "source": self.source,
            "confidence": 1.0,
            "bins": self.bins,
            "description": self.description,
        }
        return d


def _to_float(s: str) -> Optional[float]:
    s = (s or "").strip()
    if not s:
        return None
    try:
        return float(s)
    except Exception:
        # sometimes comma decimal might sneak in; last-resort normalization
        try:
            return float(s.replace(",", "."))
        except Exception:
            return None


def load_constraints_from_csv(csv_path: str | Path) -> Dict[str, Dict[str, Any]]:
    p = Path(csv_path)
    if not p.exists():
        raise FileNotFoundError(str(p))

    out: Dict[str, Dict[str, Any]] = {}

    with p.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            name = (row.get("Parameters") or "").strip()
            if not name:
                continue
            kind = (row.get("Type") or "").strip() or "unknown"
            lo = _to_float(row.get("Lower Limit") or "")
            hi = _to_float(row.get("Upper Limit") or "")
            desc = (row.get("Descriptive Limit") or "").strip()
            bins = (row.get("Bins") or "").strip()

            c = CsvConstraint(
                name=name,
                kind=kind,
                min_value=lo,
                max_value=hi,
                description=desc,
                bins=bins,
                source=str(p),
            )
            out[name] = c.to_pipeline_dict()

    return out


def merge_constraints(*constraint_dicts: Dict[str, Dict[str, Any]]) -> Dict[str, Dict[str, Any]]:
    """Right-most dict wins on conflicts."""
    merged: Dict[str, Dict[str, Any]] = {}
    for d in constraint_dicts:
        merged.update(d)
    return merged


def load_block_constraints(block_name: str, data_dir: str | Path = "data") -> Dict[str, Dict[str, Any]]:
    """
    Auto-detect and load all CSV constraint files for a given block.
    
    Searches for files matching: data/param_limits_{block_name}*.csv
    
    Examples:
        - block_name="filter_3p3z" → loads df1_q23.csv, df2_f32.csv, hw_ppca.csv
        - block_name="mppt" → loads mppt_pno.csv
        - block_name="ac_rms_pll" → loads ac_rms_pll_1phase.csv, _3phase.csv, _3phasedd.csv
    
    Returns:
        Merged constraints dict, or {} if no CSV files found
    """
    data_path = Path(data_dir)
    if not data_path.exists():
        return {}
    
    # Find all CSV files for this block
    pattern = f"param_limits_{block_name}*.csv"
    csv_files = list(data_path.glob(pattern))
    
    if not csv_files:
        # No CSV constraints for this block
        return {}
    
    # Load and merge all variants
    all_constraints = []
    for csv_file in sorted(csv_files):
        try:
            constraints = load_constraints_from_csv(csv_file)
            all_constraints.append(constraints)
        except Exception as e:
            # Log warning but don't fail
            import sys
            print(f"Warning: Failed to load {csv_file.name}: {e}", file=sys.stderr)
    
    return merge_constraints(*all_constraints) if all_constraints else {}


def find_numeric_range_anomalies(constraints: Dict[str, Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Return a list of constraints with obvious numeric range issues."""
    anomalies: List[Dict[str, Any]] = []
    for name, c in (constraints or {}).items():
        lo = c.get("min")
        hi = c.get("max")
        try:
            if lo is None or hi is None:
                continue
            lo_f = float(lo)
            hi_f = float(hi)
            if lo_f > hi_f:
                anomalies.append({"parameter": name, "min": lo, "max": hi, "reason": "min>max"})
        except Exception:
            anomalies.append({"parameter": name, "min": lo, "max": hi, "reason": "non-numeric min/max"})
    return anomalies

