"""Agent 0: Harness builder (boilerplate, optional).

This module is intentionally **non-invasive**:
- It does NOT affect the existing pipeline unless explicitly invoked.
- It is designed as Phase-2 work: automate onboarding once the user provides
  a target entrypoint (function) and a build command.

HLD
---
Inputs:
- target_repo: path to repo under test
- entrypoint: function name (user-provided)
- build_cmd: how to build the target in host mode (user-provided)
- include_dirs / extra_sources: optional

Outputs (run-scoped recommended):
- generated harness source (C/C++)
- build wrapper script (or command line)
- a small verification report (JSON)

Verification loop (T6-safe idea)
-------------------------------
We verify in deterministic steps and fail early:
1) Build check: run user-provided build command
2) Harness compile: compile the harness + link to target artifacts
3) Smoke run: execute harness on a trivial seed file
4) Timeout safety: ensure harness terminates quickly
5) Side-effect safety (best-effort): run in restricted cwd and document limitations

NOTE
----
This is a scaffold. Real automation requires per-repo adapters.
"""

from __future__ import annotations

import json
import subprocess
import time
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import List, Optional


@dataclass
class HarnessBuildSpec:
    target_repo: str
    entrypoint: str
    language: str = "c"  # c|cpp
    build_cmd: Optional[List[str]] = None
    include_dirs: Optional[List[str]] = None
    extra_sources: Optional[List[str]] = None


@dataclass
class HarnessBuildResult:
    status: str  # completed|error
    output_dir: str
    harness_source: Optional[str] = None
    harness_binary: Optional[str] = None
    verification_json: Optional[str] = None
    error: Optional[str] = None


def generate_harness_source(*, entrypoint: str, language: str = "c") -> str:
    """Generate a minimal AFL++-style harness source.

    This is intentionally generic: it calls the named entrypoint with a byte buffer.
    For real repos, you often need decoding and initialization.
    """

    if language not in {"c", "cpp"}:
        language = "c"

    extern = "extern \"C\"" if language == "cpp" else ""

    return f"""// AUTOGENERATED (Agent0 harness builder)\n\
// NOTE: This is a generic harness stub. You must adapt argument decoding/initialization.\n\
\n\
#include <stdint.h>\n\
#include <stddef.h>\n\
#include <stdio.h>\n\
#include <stdlib.h>\n\
\n\
{extern} int {entrypoint}(const uint8_t* data, size_t size);\n\
\n\
static int read_file(const char* path, uint8_t** out, size_t* out_sz) {{\n\
  FILE* f = fopen(path, \"rb\");\n\
  if (!f) return 2;\n\
  fseek(f, 0, SEEK_END);\n\
  long n = ftell(f);\n\
  fseek(f, 0, SEEK_SET);\n\
  if (n < 0) {{ fclose(f); return 2; }}\n\
  uint8_t* buf = (uint8_t*)malloc((size_t)n);\n\
  if (!buf) {{ fclose(f); return 2; }}\n\
  if (fread(buf, 1, (size_t)n, f) != (size_t)n) {{ fclose(f); free(buf); return 2; }}\n\
  fclose(f);\n\
  *out = buf;\n\
  *out_sz = (size_t)n;\n\
  return 0;\n\
}}\n\
\n\
int main(int argc, char** argv) {{\n\
  if (argc < 2) return 2;\n\
  uint8_t* data = NULL;\n\
  size_t sz = 0;\n\
  if (read_file(argv[1], &data, &sz) != 0) return 2;\n\
  int rc = {entrypoint}(data, sz);\n\
  free(data);\n\
  return rc;\n\
}}\n"""


def build_and_verify(*, spec: HarnessBuildSpec, out_dir: str, timeout_s: int = 10) -> HarnessBuildResult:
    odir = Path(out_dir)
    odir.mkdir(parents=True, exist_ok=True)

    src_ext = "cpp" if spec.language == "cpp" else "c"
    harness_src = odir / f"harness_autogen.{src_ext}"
    harness_src.write_text(generate_harness_source(entrypoint=spec.entrypoint, language=spec.language), encoding="utf-8")

    verification = {
        "startedAt": time.time(),
        "steps": [],
        "spec": asdict(spec),
    }

    try:
        # Step 1: run user build (optional)
        if spec.build_cmd:
            p = subprocess.run(spec.build_cmd, cwd=spec.target_repo, timeout=timeout_s)
            verification["steps"].append({"name": "repo_build", "returncode": p.returncode})
            if p.returncode != 0:
                raise RuntimeError("repo build failed")

        # Step 2: compile harness (best-effort; user still needs to supply link flags in reality)
        harness_bin = odir / "harness_autogen"
        cc = "clang++" if spec.language == "cpp" else "clang"
        cmd = [cc, "-O0", "-g", str(harness_src), "-o", str(harness_bin)]
        for inc in spec.include_dirs or []:
            cmd += ["-I", inc]
        for src in spec.extra_sources or []:
            cmd += [src]

        p2 = subprocess.run(cmd, cwd=spec.target_repo, timeout=timeout_s)
        verification["steps"].append({"name": "harness_compile", "returncode": p2.returncode, "cmd": cmd})
        if p2.returncode != 0:
            raise RuntimeError("harness compile failed (missing link args expected)")

        # Step 3: smoke run
        seed = odir / "seed_0000.bin"
        seed.write_bytes(b"\x00")
        p3 = subprocess.run([str(harness_bin), str(seed)], cwd=str(odir), timeout=timeout_s)
        verification["steps"].append({"name": "smoke_run", "returncode": p3.returncode})

        ver_path = odir / "verification.json"
        ver_path.write_text(json.dumps(verification, indent=2), encoding="utf-8")

        return HarnessBuildResult(
            status="completed",
            output_dir=str(odir),
            harness_source=str(harness_src),
            harness_binary=str(harness_bin),
            verification_json=str(ver_path),
        )

    except Exception as e:
        verification["error"] = str(e)
        ver_path = odir / "verification.json"
        ver_path.write_text(json.dumps(verification, indent=2), encoding="utf-8")
        return HarnessBuildResult(status="error", output_dir=str(odir), harness_source=str(harness_src), verification_json=str(ver_path), error=str(e))
